# Generated by Django 3.1.5 on 2021-02-12 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mag', models.DecimalField(decimal_places=1, max_digits=2)),
                ('s_lat', models.DecimalField(decimal_places=3, max_digits=3)),
                ('s_long', models.DecimalField(decimal_places=3, max_digits=3)),
                ('d_fis', models.DecimalField(decimal_places=1, max_digits=2)),
                ('d_sen', models.DecimalField(decimal_places=1, max_digits=2)),
                ('u', models.DecimalField(decimal_places=1, max_digits=2)),
                ('p_lat', models.DecimalField(decimal_places=5, max_digits=8)),
                ('p_long', models.DecimalField(decimal_places=5, max_digits=8)),
                ('p', models.DecimalField(decimal_places=1, max_digits=2)),
                ('v', models.DecimalField(decimal_places=1, max_digits=2)),
                ('ir', models.DecimalField(decimal_places=2, max_digits=2)),
                ('sem', models.CharField(max_length=10)),
            ],
        ),
    ]
