# Generated by Django 3.1.5 on 2021-02-12 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caso',
            name='p_lat',
            field=models.DecimalField(decimal_places=5, max_digits=9),
        ),
        migrations.AlterField(
            model_name='caso',
            name='p_long',
            field=models.DecimalField(decimal_places=5, max_digits=9),
        ),
    ]
