# Generated by Django 3.1.5 on 2021-02-12 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulacion', '0002_auto_20210212_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caso',
            name='ir',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
