# Generated by Django 3.1.5 on 2021-02-17 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulacion', '0003_auto_20210212_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caso',
            name='s_lat',
            field=models.DecimalField(decimal_places=3, max_digits=9),
        ),
        migrations.AlterField(
            model_name='caso',
            name='s_long',
            field=models.DecimalField(decimal_places=3, max_digits=9),
        ),
    ]
